### ISSUE TITLE
Not clear how to work  multiple CD albums

### ISSUE THREAD

**Issue by wdysun** [jesseward/discogstagger#40]
I read the user guide here, and I went through the code. I see that in the config file there are options about multi-discs issues. However, is not really clear how to tag them. 

What's the typical strategy? I tried to put the files into two directories with various names: I tried CD01 and CD02, also 1-CD and 2-CD, etc. But none of this worked.

How to do it?

**Comment by joldnl** [comment]
It also fails with filenames `1-1.mp3` to `1-22.mp3` and `2-1.mp3` to `2-20.mp3` in the same directory without any other files or subdirs. 

I'm a bit confused as there is documentation in the config on how to treat multi-cd releases.
Would be nice if this can be clarified as the rest of the script is very powerful and a fundament of my processing tools.

Command: `discogs-tagger -s ./ -r 8921070`

Returned error data:
```2025-04-16 22:52:59,709 discogstagger.discogsalbum INFO     Fetching discogs release. artist=The Ramblers, title=Farewell Blues, id=8921070
Traceback (most recent call last):
  File "/home/jurgen/.virtualenvs/discogstagger/bin/discogs-tagger", line 33, in <module>
    sys.exit(load_entry_point('discogstagger==3.0.3', 'console_scripts', 'discogs-tagger')())
  File "/home/jurgen/.virtualenvs/discogstagger/lib/python3.10/site-packages/click-8.1.8-py3.10.egg/click/core.py", line 1161, in __call__
    return self.main(*args, **kwargs)
  File "/home/jurgen/.virtualenvs/discogstagger/lib/python3.10/site-packages/click-8.1.8-py3.10.egg/click/core.py", line 1082, in main
    rv = self.invoke(ctx)
  File "/home/jurgen/.virtualenvs/discogstagger/lib/python3.10/site-packages/click-8.1.8-py3.10.egg/click/core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jurgen/.virtualenvs/discogstagger/lib/python3.10/site-packages/click-8.1.8-py3.10.egg/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)
  File "/home/jurgen/.virtualenvs/discogstagger/lib/python3.10/site-packages/discogstagger-3.0.3-py3.10.egg/discogstagger/main.py", line 255, in tagger
  File "/home/jurgen/.virtualenvs/discogstagger/lib/python3.10/site-packages/discogstagger-3.0.3-py3.10.egg/discogstagger/taggerutils.py", line 38, in __init__
  File "/home/jurgen/.virtualenvs/discogstagger/lib/python3.10/site-packages/discogstagger-3.0.3-py3.10.egg/discogstagger/taggerutils.py", line 151, in _get_tag_map
  File "/home/jurgen/.virtualenvs/discogstagger/lib/python3.10/site-packages/discogstagger-3.0.3-py3.10.egg/discogstagger/taggerutils.py", line 81, in _value_from_tag
  File "/home/jurgen/.virtualenvs/discogstagger/lib/python3.10/site-packages/discogstagger-3.0.3-py3.10.egg/discogstagger/taggerutils.py", line 60, in _value_from_tag_format
  File "/home/jurgen/.virtualenvs/discogstagger/lib/python3.10/site-packages/discogstagger-3.0.3-py3.10.egg/discogstagger/discogsalbum.py", line 158, in style
IndexError: list index out of range```
